### ISSUE TITLE
Modify build so that links in docs.micronaut.io are links versioned as specified in the BOM

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-docs-index#101]
see: https://github.com/micronaut-projects/scripts/pull/13

see: https://github.com/micronaut-projects/micronaut-docs/issues/148#issuecomment-1940727230

Modify GitHub actions so that we can trigger a release and generate a new version of the docs. 

e.g. I release with tag v4.3.3 and there is a page 4.3.3.html being pushed to gh-pages branch

**Comment by timyates** [comment]
@sdelamo do we care about old patch versions? Instead of `4.3.3.html`, we could just create `4.3.x.html` which would write over the previous patch?

**Comment by sdelamo** [comment]
we do care about patch versions.
