### ISSUE TITLE
Add control-panel as snapshot to docs

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-docs-index#65]
Since the modele is not yet released we have to add it as snapshot. I missed that here: 

https://github.com/micronaut-projects/micronaut-docs-index/pull/64

**Comment by alvarosanchez** [comment]
The module is released: https://repo.maven.apache.org/maven2/io/micronaut/controlpanel/micronaut-control-panel-bom/1.0.0-M1/

**Comment by sdelamo** [comment]
Documentation is not reachable https://micronaut-projects.github.io/micronaut-control-panel/latest/guide

**Comment by sdelamo** [comment]
Moreover, the module currently is in the build category. I think we have to move it t Misc maybe Views category.
