### ISSUE TITLE
Consider creating a Dev & Test category

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-docs-index#72]
I would like to create a group named `Dev & Test` in https://docs.micronaut.io and move the following modules into it: 

- Micronaut Test
- Micronaut Test Resources
- Micronaut Control Panel

@micronaut-projects/core-developers Thoughts?

**Comment by dstepanov** [comment]
Sure.

Looking at it:
- I would display the guides link in the blue box. Some people might prefer that. It's getting lost in the menu dropdown
- The second box is a bit confusing as it is Core documentation. It might be worse to mention it
- I would move the Micronaut Data section more up or replace the snapshot box with popular and put quick links for data, security etc docs

**Comment by sdelamo** [comment]
good ideas @dstepanov I will create separate issues.

**Comment by sdelamo** [comment]
Close https://github.com/micronaut-projects/micronaut-docs-index/pull/76
