### ISSUE TITLE
Renaming latest documentation to core documentation

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-docs-index#73]
@dstepanov 

> The second box is a bit confusing as it is Core documentation. It might be worse to mention it

we could replace: 

![CleanShot 2023-07-31 at 15 25 26](https://github.com/micronaut-projects/micronaut-docs-index/assets/864788/b96c466f-e612-479b-9f61-93aaa8c6aef8)

with: 

![CleanShot 2023-07-31 at 15 25 55](https://github.com/micronaut-projects/micronaut-docs-index/assets/864788/5580a753-5043-42fb-9857-a2dc608a6cc3)

Maybe, we should not list snapshot docs. 

@micronaut-projects/core-developers thoughts?

**Comment by melix** [comment]
Fine for me. I would go even further by removing, or moving farther, the snapshot documentation since it's extremely unlikely that a normal user would ever use a snapshot.

**Comment by sdelamo** [comment]
I think we should [link to guides instead of snapshot](https://github.com/micronaut-projects/micronaut-docs-index/issues/75)

**Comment by wetted** [comment]
I like the idea of linking guides instead of SNAPSHOT docs. The latter seems mostly of interest to us, maybe for the most part when we're working on a new major.
