### ISSUE TITLE
Consider replacing snapshot docs with another link to guides

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-docs-index#75]
@dstepanov 

> I would display the guides link in the blue box. Some people might prefer that. It's getting lost in the menu dropdown

I think we should replace link to snapshot to guides. 

![CleanShot 2023-07-31 at 16 04 34](https://github.com/micronaut-projects/micronaut-docs-index/assets/864788/bea186fe-9f4a-4af0-b9df-0ce4bb835f09)

@micronaut-projects/core-developers thoughts?

**Comment by dstepanov** [comment]
My suggestion was to put it to the blue box. Something like: See guides here

**Comment by dstepanov** [comment]
The box on the right can be popular links

**Comment by sdelamo** [comment]
I don't think we should replace the blue box. We use that style thought the site and it is never a link to something else. I think the blue box have to stay.
